import{a as b,S as w,i as a}from"./assets/vendor-Dy2ZTtfi.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const v="51344129-a8075834a2d0391c119eb3239";async function u(o,n,e){try{return(await b.get("https://pixabay.com/api/",{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:e}})).data}catch(r){throw r}}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more"),S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const n=o.map(e=>`
        <li class="gallery-item">
        <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",n),S.refresh()}function q(){f.innerHTML=""}function y(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}function $(){p.classList.remove("is-hidden")}function L(){p.classList.add("is-hidden")}const M=document.querySelector(".form"),P=document.querySelector(".gallery"),x=document.querySelector(".load-more");let i=1,c=15,d="";M.addEventListener("submit",B);x.addEventListener("click",E);async function B(o){o.preventDefault();const e=o.currentTarget.elements["search-text"].value.trim();if(e){d=e,i=1,q(),L(),y();try{const r=await u(d,i,c);if(r.hits.length===0){a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(r.hits),r.totalHits>c&&$()}catch(r){console.error("Помилка при отриманні зображення:",r),a.info({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}}async function E(){i+=1,y();try{const o=await u(d,i,c);m(o.hits);const{height:n}=P.firstElementChild.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"}),i*c>=o.totalHits&&(L(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.log("Помилка при завантаженні наступної сторінки:",o),a.error({title:"Error",message:"Could not load more images.",position:"topRight"})}finally{g()}}
//# sourceMappingURL=index.js.map
